version: "2.2"

services:
  core:
    build: bot/
    restart: always
    environment:
      bot_nickname: UnboundMedia
      utopia_host: utopia-api
      utopia_token: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      utopia_port: 22825
      db_host: db
      db_user: root
      db_pass: pass
      db_name: diano
      db_enabled: 1
      max_file_size_mb: 10
      is_debug: 1
      CRON_SPEC: every 1m
      DISABLE_ENV_PARSE: 1
    depends_on:
      - utopia-api
      - db
    networks:
      - unetwork
    volumes:
      - './redirects:/app/cache'
    stdin_open: true
    tty: true

  utopia-api:
    image: uto9234/utopia-api
    hostname: utopia-api
    restart: always
    ports:
      - 22825:22825
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-root
    networks:
      - unetwork
    volumes:
      - type: bind
        source: ./account.db
        target: /app/account.db
    logging:
      driver: none

  db:
    command: mkdir db
    image: mysql:5.7
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "diano"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - 3318:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./bot/db_dump.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - unetwork
    logging:
      driver: none

networks:
  unetwork:

volumes:
  redirects:
